"""Deterministic Pelican starting point for a new customer website."""

from __future__ import annotations

from pathlib import Path


def _write(root: Path, relative: str, content: str) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def initialize_site(directory: str | Path, name: str = "New Website", url: str = "") -> Path:
    """Create the standard Pelican files in an empty customer repository."""
    root = Path(directory).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        raise FileExistsError(f"site directory is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)
    site_name = str(name or "New Website").strip()
    site_url = str(url or "").strip().rstrip("/")
    _write(root, "pelicanconf.py", f'''"""Pelican settings generated by site-agent."""

AUTHOR = "Ada"
SITENAME = {site_name!r}
SITEURL = {site_url!r}
PATH = "content"
OUTPUT_PATH = "output"
TIMEZONE = "UTC"
DEFAULT_LANG = "en"
THEME = "themes/ada"
PAGE_PATHS = ["pages"]
ARTICLE_PATHS = ["articles"]
PAGE_SAVE_AS = "{{slug}}.html"
PAGE_URL = "{{slug}}.html"
ARTICLE_SAVE_AS = "articles/{{slug}}.html"
ARTICLE_URL = "articles/{{slug}}.html"
INDEX_SAVE_AS = "articles.html"
DIRECT_TEMPLATES = ["index"]
DEFAULT_PAGINATION = False
''')
    _write(root, "build.sh", """#!/usr/bin/env bash
set -euo pipefail
rm -rf output
pelican content -o output -s pelicanconf.py

# output/ is the public boundary; remove accidental source/template copies
# rather than failing a customer deployment.
for forbidden in content themes pelicanconf.py build.sh requirements.txt; do
  if [ -e "output/$forbidden" ]; then
    printf 'public output guard: removed forbidden path: output/%s\\n' "$forbidden" >&2
    rm -rf "output/$forbidden"
  fi
done
for pattern in '*.jinja' '*.jinja2' '*.j2' '*.yaml' '*.yml'; do
  while IFS= read -r leaked; do
    [ -n "$leaked" ] || continue
    printf 'public output guard: removed template/config file: %s\\n' "$leaked" >&2
    rm -f "$leaked"
  done < <(find output -type f -name "$pattern" -print)
done
""")
    (root / "build.sh").chmod(0o755)
    _write(root, "requirements.txt", "pelican>=4.9,<5\nMarkdown>=3.4,<4\n")
    _write(root, "content/pages/index.md", f'''Title: Home
Slug: index

# {site_name}

This homepage is ready for Ada's first design pass.
''')
    _write(root, "content/pages/about.md", """Title: About
Slug: about

This page is a placeholder for the business story and customer promise.
""")
    _write(root, "content/pages/contact.md", """Title: Contact
Slug: contact

This page is a placeholder for the primary customer action.
""")
    _write(root, "content/articles/.gitkeep", "")
    _write(root, "themes/ada/templates/base.html", """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ SITENAME }}{% endblock %}</title>
  <link rel="stylesheet" href="{{ SITEURL }}/theme/css/site.css">
</head>
<body>
  <header><span class="ada-mark">Ada · {{ SITENAME }}</span></header>
  {% block content %}{% endblock %}
</body>
</html>
""")
    _write(root, "themes/ada/templates/page.html", """{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ SITENAME }}{% endblock %}
{% block content %}<main><article>{{ page.content }}</article></main>{% endblock %}
""")
    _write(root, "themes/ada/templates/index.html", """{% extends "base.html" %}
{% block title %}Ada's journal · {{ SITENAME }}{% endblock %}
{% block content %}
<main>
  <h1>Ada's journal</h1>
  {% if articles %}
    {% for article in articles %}<article><h2><a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }}</a></h2>{{ article.summary }}</article>{% endfor %}
  {% else %}<article><h2>Ada is ready to write.</h2><p>The blog is ready for the first customer-specific article.</p></article>{% endif %}
</main>
{% endblock %}
""")
    _write(root, "themes/ada/templates/article.html", """{% extends "base.html" %}
{% block title %}{{ article.title }} · {{ SITENAME }}{% endblock %}
{% block content %}<main><article><h1>{{ article.title }}</h1><p class="byline">Written by Ada</p>{{ article.content }}</article></main>{% endblock %}
""")
    _write(root, "themes/ada/static/css/site.css", """body{margin:0;color:#17313b;background:#f5f8f8;font:16px/1.6 system-ui,sans-serif}main{max-width:760px;margin:48px auto;padding:0 24px}article{background:white;border:1px solid #dce8e8;border-radius:12px;padding:28px;margin:18px 0}a{color:#087f99}.ada-mark{display:block;padding:24px;color:#087f99;font-size:12px;letter-spacing:.12em;text-transform:uppercase}.byline{color:#58727b;font-size:13px}""")
    return root
