"""Site bootstrap helpers.

The long-standing ``initialize_site`` API creates the legacy Pelican site used
by existing customer repositories and the ``init-site`` command.  New
from-scratch design experiments must use ``initialize_toolchain_workspace``;
that initializer deliberately contains no visual implementation.
"""

from __future__ import annotations

import json
from pathlib import Path


def _write(root: Path, relative: str, content: str) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def initialize_site(directory: str | Path, name: str = "New Website", url: str = "") -> Path:
    """Create the legacy Pelican files for an existing/legacy site workflow."""
    root = Path(directory).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        raise FileExistsError(f"site directory is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)
    site_name = str(name or "New Website").strip()
    site_url = str(url or "").strip().rstrip("/")
    _write(root, "pelicanconf.py", f'''"""Pelican settings generated by site-agent."""

AUTHOR = "Ada"
SITENAME = {site_name!r}
SITEURL = {site_url!r}
PATH = "content"
OUTPUT_PATH = "output"
TIMEZONE = "UTC"
DEFAULT_LANG = "en"
THEME = "themes/ada"
PAGE_PATHS = ["pages"]
ARTICLE_PATHS = ["articles"]
PAGE_SAVE_AS = "{{slug}}.html"
PAGE_URL = "{{slug}}.html"
ARTICLE_SAVE_AS = "articles/{{slug}}.html"
ARTICLE_URL = "articles/{{slug}}.html"
INDEX_SAVE_AS = "articles.html"
DIRECT_TEMPLATES = ["index"]
DEFAULT_PAGINATION = False
''')
    _write(root, "build.sh", """#!/usr/bin/env bash
set -euo pipefail
rm -rf output
pelican content -o output -s pelicanconf.py

# output/ is the public boundary; remove accidental source/template copies
# rather than failing a customer deployment.
for forbidden in content themes pelicanconf.py build.sh requirements.txt; do
  if [ -e "output/$forbidden" ]; then
    printf 'public output guard: removed forbidden path: output/%s\\n' "$forbidden" >&2
    rm -rf "output/$forbidden"
  fi
done
for relative in index.html styles.css app.js vendor images; do
  if [ -e "$relative" ]; then
    rm -rf "output/$relative"
    if [ -d "$relative" ]; then
      cp -R "$relative" "output/$relative"
    else
      cp "$relative" "output/$relative"
    fi
  fi
done
for pattern in '*.jinja' '*.jinja2' '*.j2' '*.yaml' '*.yml'; do
  while IFS= read -r leaked; do
    [ -n "$leaked" ] || continue
    printf 'public output guard: removed template/config file: %s\\n' "$leaked" >&2
    rm -f "$leaked"
  done < <(find output -type f -name "$pattern" -print)
done
""")
    (root / "build.sh").chmod(0o755)
    _write(root, "requirements.txt", "pelican>=4.9,<5\nMarkdown>=3.4,<4\n")
    _write(root, "content/pages/index.md", f'''Title: Home
Slug: index

# {site_name}

This homepage is ready for Ada's first design pass.
''')
    _write(root, "content/pages/about.md", """Title: About
Slug: about

This page is a placeholder for the business story and customer promise.
""")
    _write(root, "content/pages/contact.md", """Title: Contact
Slug: contact

This page is a placeholder for the primary customer action.
""")
    _write(root, "content/articles/.gitkeep", "")
    _write(root, "themes/ada/templates/base.html", """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ SITENAME }}{% endblock %}</title>
  <link rel="stylesheet" href="{{ SITEURL }}/theme/css/site.css">
</head>
<body>
  <header><span class="ada-mark">Ada · {{ SITENAME }}</span></header>
  {% block content %}{% endblock %}
</body>
</html>
""")
    _write(root, "themes/ada/templates/page.html", """{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ SITENAME }}{% endblock %}
{% block content %}<main><article>{{ page.content }}</article></main>{% endblock %}
""")
    _write(root, "themes/ada/templates/index.html", """{% extends "base.html" %}
{% block title %}Ada's journal · {{ SITENAME }}{% endblock %}
{% block content %}
<main>
  <h1>Ada's journal</h1>
  {% if articles %}
    {% for article in articles %}<article><h2><a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }}</a></h2>{{ article.summary }}</article>{% endfor %}
  {% else %}<article><h2>Ada is ready to write.</h2><p>The blog is ready for the first customer-specific article.</p></article>{% endif %}
</main>
{% endblock %}
""")
    _write(root, "themes/ada/templates/article.html", """{% extends "base.html" %}
{% block title %}{{ article.title }} · {{ SITENAME }}{% endblock %}
{% block content %}<main><article><h1>{{ article.title }}</h1><p class="byline">Written by Ada</p>{{ article.content }}</article></main>{% endblock %}
""")
    _write(root, "themes/ada/static/css/site.css", """body{margin:0;color:#17313b;background:#f5f8f8;font:16px/1.6 system-ui,sans-serif}main{max-width:760px;margin:48px auto;padding:0 24px}article{background:white;border:1px solid #dce8e8;border-radius:12px;padding:28px;margin:18px 0}a{color:#087f99}.ada-mark{display:block;padding:24px;color:#087f99;font-size:12px;letter-spacing:.12em;text-transform:uppercase}.byline{color:#58727b;font-size:13px}""")
    return root


_ASTRO_VERSION = "5.18.2"
_ASTRO_REACT_VERSION = "4.4.2"
_GSAP_REACT_VERSION = "2.1.2"
_REACT_VERSION = "19.2.8"
_REACT_DOM_VERSION = "19.2.8"
_GSAP_VERSION = "3.12.5"
_CHECK_VERSION = "0.9.10"
_TYPES_NODE_VERSION = "22.20.1"
_TYPES_REACT_VERSION = "19.2.18"
_TYPES_REACT_DOM_VERSION = "19.2.5"
_TYPESCRIPT_VERSION = "5.9.3"


def _package_manifest(name: str) -> dict[str, object]:
    """Return exact direct toolchain dependencies, with no visual defaults."""
    return {
        "name": f"ada-{name.lower().replace(' ', '-')}-site" if name else "ada-site",
        "private": True,
        "type": "module",
        "scripts": {
            "check": "astro check",
            "build": "astro build",
            "preview": "astro preview",
        },
        "dependencies": {
            "@astrojs/react": _ASTRO_REACT_VERSION,
            "@gsap/react": _GSAP_REACT_VERSION,
            "astro": _ASTRO_VERSION,
            "gsap": _GSAP_VERSION,
            "react": _REACT_VERSION,
            "react-dom": _REACT_DOM_VERSION,
        },
        "devDependencies": {
            "@astrojs/check": _CHECK_VERSION,
            "@types/node": _TYPES_NODE_VERSION,
            "@types/react": _TYPES_REACT_VERSION,
            "@types/react-dom": _TYPES_REACT_DOM_VERSION,
            "typescript": _TYPESCRIPT_VERSION,
        },
    }


def initialize_toolchain_workspace(directory: str | Path, name: str = "") -> Path:
    """Create a blank Astro/React workspace for a new design experiment.

    This is intentionally not a site template: it creates only package/config
    metadata and empty source directories.  The first page, styles, copy,
    imagery, fonts, components, and motion are authored by the isolated model.
    """
    root = Path(directory).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        raise FileExistsError(f"site directory is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)

    _write(root, "package.json", json.dumps(_package_manifest(str(name or "")), indent=2) + "\n")
    _write(root, "astro.config.mjs", """import { defineConfig } from 'astro/config';
import react from '@astrojs/react';

export default defineConfig({
  integrations: [react()],
});
""")
    _write(root, "tsconfig.json", """{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  }
}
""")
    _write(root, ".gitignore", """node_modules/
dist/
.astro/
.opencode/
.agent-home/
""")
    for relative in (
        "src/pages/.gitkeep",
        "src/components/.gitkeep",
        "src/styles/.gitkeep",
        "public/.gitkeep",
        "design/.gitkeep",
    ):
        _write(root, relative, "")
    _write(root, "src/env.d.ts", "/// <reference types=\"astro/client\" />\n")
    return root


__all__ = ["initialize_site", "initialize_toolchain_workspace"]
