export const growthTaskCopy: Record<string, Record<string, string>> = {
  en: {
    overview: "Your growth plan", taskTitle: "Your growth plan", taskNote: "Ada prepares. You decide. Everything stays in one place.",
    taskFocus: "Filter the growth plan", task_all: "All work", task_needs_you: "Needs you", task_preparing: "Ada preparing", task_planned: "Planned", task_completed: "Completed",
    taskEmpty: "Nothing in this view. Other work is available in the filters above.", taskFailed: "The action could not be completed. No success has been assumed.",
    taskBlocked: "Ada needs to resolve:", taskBefore: "Current version", taskAfter: "Proposed version", taskApprove: "Approve this version", taskDecline: "Decline",
    scheduled: "Scheduled", queued: "Queued", running: "Ada working", blocked: "Ada resolving", taskState_reviewed: "Results reviewed", taskState_rejected: "Declined", taskState_superseded: "Replaced",
    taskResults: "Observed results", taskDays: "days", taskConfidence: "Confidence", taskHistory: "Earlier versions",
    result_positive: "Improvement observed", result_negative: "Decrease observed", result_neutral: "No material change", result_inconclusive: "Not enough comparable data",
    confidence_low: "Low", confidence_medium: "Moderate", confidence_high: "High",
    taskState_measuring: "Live · observing results", taskState_blocked: "Ada resolving", taskState_publishing: "Publishing",
    taskState_verifying_live: "Checking the live site", taskState_snoozed: "Deferred", taskState_ready_for_review: "Ready for your review",
    growth_initial: "First website review", growth_daily: "Refresh traffic, search & results", growth_weekly: "Prepare your next improvements", growth_monthly: "Keyword & competitor research", paused: "Paused",
  },
  fr: {
    overview: "Votre programme", taskTitle: "Votre programme de croissance", taskNote: "Ada prépare. Vous décidez. Tout reste au même endroit.",
    taskFocus: "Filtrer le programme", task_all: "Tout", task_needs_you: "À vous de décider", task_preparing: "Ada prépare", task_planned: "Planifié", task_completed: "Terminé",
    taskEmpty: "Rien dans cette vue. Les autres travaux sont accessibles avec les filtres ci-dessus.", taskFailed: "L’action n’a pas abouti. Aucune réussite n’a été supposée.",
    taskBlocked: "Ada doit résoudre :", taskBefore: "Version actuelle", taskAfter: "Version proposée", taskApprove: "Approuver cette version", taskDecline: "Refuser",
    scheduled: "Planifié", queued: "En attente", running: "Ada travaille", blocked: "Ada doit résoudre", taskState_reviewed: "Résultats analysés", taskState_rejected: "Refusé", taskState_superseded: "Remplacé",
    taskResults: "Résultats observés", taskDays: "jours", taskConfidence: "Confiance", taskHistory: "Versions précédentes",
    result_positive: "Amélioration observée", result_negative: "Baisse observée", result_neutral: "Pas de changement notable", result_inconclusive: "Données comparables insuffisantes",
    confidence_low: "Faible", confidence_medium: "Modérée", confidence_high: "Élevée",
    taskState_measuring: "En ligne · suivi des résultats", taskState_blocked: "Ada doit résoudre", taskState_publishing: "Publication",
    taskState_verifying_live: "Vérification du site en ligne", taskState_snoozed: "Reporté", taskState_ready_for_review: "Prêt à valider",
    growth_initial: "Première analyse du site", growth_daily: "Actualiser les visites, recherches et résultats", growth_weekly: "Préparer les prochaines améliorations", growth_monthly: "Recherche de mots-clés et concurrents", paused: "En pause",
  },
  es: {
    overview: "Tu plan de crecimiento", taskTitle: "Tu plan de crecimiento", taskNote: "Ada prepara. Tú decides. Todo está en un solo lugar.",
    taskFocus: "Filtrar el plan", task_all: "Todo", task_needs_you: "Te toca decidir", task_preparing: "Ada está preparando", task_planned: "Programado", task_completed: "Terminado",
    taskEmpty: "No hay trabajo en esta vista. Usa los filtros para ver lo demás.", taskFailed: "No se pudo completar la acción. No se ha dado por exitosa.",
    taskBlocked: "Ada necesita resolver:", taskBefore: "Versión actual", taskAfter: "Versión propuesta", taskApprove: "Aprobar esta versión", taskDecline: "Rechazar",
    scheduled: "Programado", queued: "En espera", running: "Ada está trabajando", blocked: "Ada está resolviendo", taskState_reviewed: "Resultados revisados", taskState_rejected: "Rechazado", taskState_superseded: "Reemplazado",
    taskResults: "Resultados observados", taskDays: "días", taskConfidence: "Confianza", taskHistory: "Versiones anteriores",
    result_positive: "Mejora observada", result_negative: "Disminución observada", result_neutral: "Sin cambio importante", result_inconclusive: "Faltan datos comparables",
    confidence_low: "Baja", confidence_medium: "Moderada", confidence_high: "Alta",
    taskState_measuring: "En línea · midiendo resultados", taskState_blocked: "Ada está resolviendo", taskState_publishing: "Publicando",
    taskState_verifying_live: "Verificando el sitio en línea", taskState_snoozed: "Pospuesto", taskState_ready_for_review: "Listo para tu revisión",
    growth_initial: "Primera revisión del sitio", growth_daily: "Actualizar tráfico, búsquedas y resultados", growth_weekly: "Preparar tus próximas mejoras", growth_monthly: "Investigar palabras clave y competidores", paused: "En pausa",
  },
};
