export const growthTaskCopy: Record<string, Record<string, string>> = {
  en: {
    overview: "Your growth plan", taskTitle: "Your growth plan", taskNote: "Ada prepares. You decide. Everything stays in one place.",
    taskFocus: "Filter the growth plan", task_all: "All work", task_needs_you: "Needs your decision", task_preparing: "In progress", task_planned: "Planned", task_paused: "Paused", task_completed: "Completed",
    taskEmpty: "Nothing needs your decision right now.", taskFailed: "The action could not be completed. No success has been assumed.",
    taskBlocked: "Ada is resolving an issue with this work. No action is needed from you.", taskInternalIssue: "Ada is resolving an issue with this work. No action is needed from you.", taskBefore: "Current version", taskAfter: "Proposed version", taskApprove: "Approve & publish", taskDecline: "Decline", taskApplySettings: "Apply writing guidance", taskKeepSettings: "Keep current guidance", settingsCurrent: "Current guidance", settingsProposed: "Proposed guidance", settingsNoContentChange: "This changes Ada’s future writing guidance only. Published pages and articles will not change.",
    runAnalysis: "Run analysis", recentWork: "Recent work by Ada", noRecentWork: "Completed work will appear here.", openActivity: "View activity", taskState_unscheduled: "Date not set", taskEvidence: "What this is based on", taskAffectedPage: "Affected page", settingsVoiceNotes: "What Ada would do more of", settingsAvoid: "What Ada would avoid",
    rollbackScope: "Only the website's visual code will change. Your current content, images, settings, schema and admin stay as they are.", rollbackPreview: "Preview this restored design", restoreFrontend: "Restore this website design", keepCurrentWebsite: "Keep the current website",
    scheduled: "Scheduled", queued: "Queued", running: "Ada working", blocked: "Ada resolving", taskState_reviewed: "Results reviewed", taskState_rejected: "Declined", taskState_superseded: "Replaced",
    taskResults: "Observed results", taskDays: "days", taskConfidence: "Confidence", taskHistory: "Earlier versions",
    result_positive: "Improvement observed", result_negative: "Decrease observed", result_neutral: "No material change", result_inconclusive: "Not enough comparable data",
    confidence_low: "Low", confidence_medium: "Moderate", confidence_high: "High",
    taskState_measuring: "Live · observing results", taskState_blocked: "Ada resolving", taskState_publishing: "Publishing",
    taskState_verifying_live: "Checking the live site", taskState_snoozed: "Deferred", taskState_ready_for_review: "Ready for your review",
    growth_initial: "First website review", growth_daily: "Refresh traffic, search & results", growth_weekly: "Prepare your next improvements", growth_monthly: "Keyword & competitor research", paused: "Paused",
  },
  fr: {
    overview: "Votre programme", taskTitle: "Votre programme de croissance", taskNote: "Ada prépare. Vous décidez. Tout reste au même endroit.",
    taskFocus: "Filtrer le programme", task_all: "Tout", task_needs_you: "À valider", task_preparing: "En cours", task_planned: "Planifié", task_paused: "En pause", task_completed: "Terminé",
    taskEmpty: "Aucune décision n’est attendue pour le moment.", taskFailed: "L’action n’a pas abouti. Aucune réussite n’a été supposée.",
    taskBlocked: "Ada résout un problème lié à ce travail. Aucune action n’est nécessaire de votre part.", taskInternalIssue: "Ada résout un problème lié à ce travail. Aucune action n’est nécessaire de votre part.", taskBefore: "Version actuelle", taskAfter: "Version proposée", taskApprove: "Approuver et publier", taskDecline: "Refuser", taskApplySettings: "Appliquer les consignes d’écriture", taskKeepSettings: "Garder les consignes actuelles", settingsCurrent: "Consignes actuelles", settingsProposed: "Consignes proposées", settingsNoContentChange: "Cela modifie uniquement les futures consignes d’écriture d’Ada. Les pages et articles publiés ne changent pas.",
    runAnalysis: "Lancer l’analyse", recentWork: "Activité récente d’Ada", noRecentWork: "Les travaux terminés apparaîtront ici.", openActivity: "Voir l’activité", taskState_unscheduled: "Date à définir", taskEvidence: "Éléments à l’appui", taskAffectedPage: "Page concernée", settingsVoiceNotes: "Ce qu’Ada ferait davantage", settingsAvoid: "Ce qu’Ada éviterait",
    rollbackScope: "Seul le code visuel du site changera. Le contenu, les images, les réglages, le schéma et l’interface d’administration resteront inchangés.", rollbackPreview: "Prévisualiser ce design restauré", restoreFrontend: "Restaurer ce design", keepCurrentWebsite: "Garder le site actuel",
    scheduled: "Planifié", queued: "En attente", running: "Ada travaille", blocked: "Ada doit résoudre", taskState_reviewed: "Résultats analysés", taskState_rejected: "Refusé", taskState_superseded: "Remplacé",
    taskResults: "Résultats observés", taskDays: "jours", taskConfidence: "Confiance", taskHistory: "Versions précédentes",
    result_positive: "Amélioration observée", result_negative: "Baisse observée", result_neutral: "Pas de changement notable", result_inconclusive: "Données comparables insuffisantes",
    confidence_low: "Faible", confidence_medium: "Modérée", confidence_high: "Élevée",
    taskState_measuring: "En ligne · suivi des résultats", taskState_blocked: "Ada doit résoudre", taskState_publishing: "Publication",
    taskState_verifying_live: "Vérification du site en ligne", taskState_snoozed: "Reporté", taskState_ready_for_review: "Prêt à valider",
    growth_initial: "Première analyse du site", growth_daily: "Actualiser les visites, recherches et résultats", growth_weekly: "Préparer les prochaines améliorations", growth_monthly: "Recherche de mots-clés et concurrents", paused: "En pause",
  },
  es: {
    overview: "Tu plan de crecimiento", taskTitle: "Tu plan de crecimiento", taskNote: "Ada prepara. Tú decides. Todo está en un solo lugar.",
    taskFocus: "Filtrar el plan", task_all: "Todo", task_needs_you: "Requiere tu decisión", task_preparing: "En proceso", task_planned: "Programado", task_paused: "En pausa", task_completed: "Terminado",
    taskEmpty: "Por ahora no hay decisiones pendientes.", taskFailed: "No se pudo completar la acción. No se ha dado por exitosa.",
    taskBlocked: "Ada está resolviendo un problema con esta tarea. No tienes que hacer nada.", taskInternalIssue: "Ada está resolviendo un problema con esta tarea. No tienes que hacer nada.", taskBefore: "Versión actual", taskAfter: "Versión propuesta", taskApprove: "Aprobar y publicar", taskDecline: "Rechazar", taskApplySettings: "Aplicar las pautas de escritura", taskKeepSettings: "Mantener las pautas actuales", settingsCurrent: "Pautas actuales", settingsProposed: "Pautas propuestas", settingsNoContentChange: "Esto solo cambia las pautas futuras de escritura de Ada. No modifica las páginas ni los artículos publicados.",
    runAnalysis: "Analizar el sitio", recentWork: "Actividad reciente de Ada", noRecentWork: "Aquí aparecerán las tareas terminadas.", openActivity: "Ver actividad", taskState_unscheduled: "Fecha pendiente", taskEvidence: "En qué se basa", taskAffectedPage: "Página afectada", settingsVoiceNotes: "Lo que Ada haría más", settingsAvoid: "Lo que Ada evitaría",
    rollbackScope: "Solo cambiará el código visual del sitio. El contenido, las imágenes, la configuración, el esquema y el panel de administración se conservarán.", rollbackPreview: "Ver el diseño restaurado", restoreFrontend: "Restaurar este diseño", keepCurrentWebsite: "Conservar el sitio actual",
    scheduled: "Programado", queued: "En espera", running: "Ada está trabajando", blocked: "Ada está resolviendo", taskState_reviewed: "Resultados revisados", taskState_rejected: "Rechazado", taskState_superseded: "Reemplazado",
    taskResults: "Resultados observados", taskDays: "días", taskConfidence: "Confianza", taskHistory: "Versiones anteriores",
    result_positive: "Mejora observada", result_negative: "Disminución observada", result_neutral: "Sin cambio importante", result_inconclusive: "Faltan datos comparables",
    confidence_low: "Baja", confidence_medium: "Moderada", confidence_high: "Alta",
    taskState_measuring: "En línea · midiendo resultados", taskState_blocked: "Ada está resolviendo", taskState_publishing: "Publicando",
    taskState_verifying_live: "Verificando el sitio en línea", taskState_snoozed: "Pospuesto", taskState_ready_for_review: "Listo para tu revisión",
    growth_initial: "Primera revisión del sitio", growth_daily: "Actualizar tráfico, búsquedas y resultados", growth_weekly: "Preparar tus próximas mejoras", growth_monthly: "Investigar palabras clave y competidores", paused: "En pausa",
  },
};
