export const growthCopy: Record<string, Record<string, string>> = {
  en: {
    "growth.title": "Growth",
    "growth.overview": "Overview",
    "growth.analytics": "Analytics detail",
    "growth.analyticsIntro": "Explore the GA4 and Search Console history Ada uses to make recommendations. The overview stays focused on what to do next.",
    "growth.analyticsPrompt": "Interpret my GA4 and Search Console history. Explain the most important pattern, what it means for my business, and what Ada recommends next.",
    "growth.interpretWithAda": "Interpret with Ada",
    "growth.ga4History": "Traffic history",
    "growth.gscHistory": "Search history",
    "growth.history": "Daily history",
    "growth.historyNote": "The selected date range, updated directly from the connected property.",
    "growth.date": "Date",
    "growth.views": "Page views",
    "growth.engagement": "Engagement rate",
    "growth.ctr": "Click-through rate",
    "growth.events": "Events",
    "growth.count": "Count",
    "growth.devices": "Devices",
    "growth.countries": "Countries",
    "growth.search": "Search & keywords",
    "growth.content": "Content & reports",
    "growth.connections": "Connections",
    "growth.days": "days",
    "growth.refresh": "Refresh",
    "growth.visitors": "Visitors",
    "growth.sessions": "Visits",
    "growth.clicks": "Google clicks",
    "growth.impressions": "Search appearances",
    "growth.traffic": "How people find you",
    "growth.recommendations": "Ada’s recommendations",
    "growth.ask": "Discuss with Ada",
    "growth.noRecommendations":
      "Your next recommendations will appear here, based on your business and real performance.",
    "growth.noData": "No data yet",
    "growth.unavailable":
      "This data could not load. Other tools remain available.",
    "growth.retry": "Try again",
    "growth.schedule": "Ada’s ongoing work",
    "growth.article": "Weekly article",
    "growth.seo_insight": "SEO recommendations",
    "growth.weekly_report": "Weekly owner report",
    "growth.seo_site_report_cycle": "SEO analysis",
    "growth.article_research_cycle": "Article & keyword research",
    "growth.social_post": "Social posts",
    "growth.scheduled": "Scheduled",
    "growth.notScheduled": "Not scheduled",
    "growth.next": "Next",
    "growth.manageSchedule": "Ask Ada about the plan",
    "growth.ga4": "Google Analytics · GA4",
    "growth.gsc": "Google Search Console",
    "growth.dataforseo": "Keyword research · DataForSEO",
    "growth.ga4Note": "Visitors, popular pages, and where visits come from.",
    "growth.gscNote": "Search terms, Google clicks, and search visibility.",
    "growth.dataforseoNote":
      "Research that informs keywords, useful articles, and SEO opportunities.",
    "growth.has_data": "Data available",
    "growth.collecting": "Property configured",
    "growth.configured": "Provider configured",
    "growth.verification_required": "Verification needed",
    "growth.not_configured": "Setup needed",
    "growth.setupNote":
      "Ada manages setup and analysis. The status below reflects this website—not a demo. Approvals and required access are requested before setup.",
    "growth.setup": "Review setup with Ada",
    "growth.updated": "Updated",
    "growth.approval":
      "Articles and website changes stay drafts until you approve.",
    "growth.queries": "What people search for",
    "growth.keyword": "Keyword",
    "growth.market": "Market",
    "growth.researched": "Research runs",
    "growth.volume": "Monthly searches",
    "growth.competition": "Competition",
    "growth.position": "Position",
    "growth.pages": "Popular pages",
    "growth.channels": "Traffic sources",
    "growth.articles": "Articles to review",
    "growth.ideas": "Article ideas",
    "growth.weeklyReports": "Weekly reports",
    "growth.monthlyReports": "SEO reports",
    "growth.emptyArticles":
      "Ada’s articles will appear here for review. Your blog is always available under Manage.",
    "growth.emptyResearch":
      "Your researched keywords will appear here once research has run.",
    "growth.emptyReports": "Reports will appear here as Ada completes them.",
    "growth.openBlog": "Open blog",
    "growth.activity": "All activity",
    "growth.askPrompt":
      "Explain my website performance and recommend the highest-impact next steps. Use available analytics and research; identify missing data and explain before changing anything.",
    "growth.setupPrompt":
      "Review the setup of Google Analytics, Search Console, and keyword research for my website. Explain what is already connected, what needs access or approval, and the next steps. Do not create accounts or start paid research without my approval.",
    "growth.schedulePrompt":
      "Review the ongoing plan for weekly articles, SEO recommendations, keyword research, and owner reports. Show what is enabled and propose a useful schedule. Keep articles and changes as drafts for my approval.",
  },
  fr: {
    "growth.title": "Croissance",
    "growth.overview": "Vue d’ensemble",
    "growth.analytics": "Détail des analyses",
    "growth.analyticsIntro": "Explorez l’historique GA4 et Search Console utilisé par Ada pour ses recommandations. La vue d’ensemble reste centrée sur les prochaines actions.",
    "growth.analyticsPrompt": "Interprète l’historique GA4 et Search Console de mon site. Explique la tendance la plus importante, ce qu’elle signifie pour mon activité et ce qu’Ada recommande ensuite.",
    "growth.interpretWithAda": "Interpréter avec Ada",
    "growth.ga4History": "Historique des visites",
    "growth.gscHistory": "Historique de recherche",
    "growth.history": "Historique quotidien",
    "growth.historyNote": "La période choisie, mise à jour directement depuis la propriété connectée.",
    "growth.date": "Date",
    "growth.views": "Pages vues",
    "growth.engagement": "Taux d’engagement",
    "growth.ctr": "Taux de clics",
    "growth.events": "Événements",
    "growth.count": "Nombre",
    "growth.devices": "Appareils",
    "growth.countries": "Pays",
    "growth.search": "Recherche et mots-clés",
    "growth.content": "Articles et rapports",
    "growth.connections": "Connexions",
    "growth.days": "jours",
    "growth.refresh": "Actualiser",
    "growth.visitors": "Visiteurs",
    "growth.sessions": "Visites",
    "growth.clicks": "Clics Google",
    "growth.impressions": "Apparitions dans Google",
    "growth.traffic": "Comment on vous trouve",
    "growth.recommendations": "Les recommandations d’Ada",
    "growth.ask": "En parler avec Ada",
    "growth.noRecommendations":
      "Vos prochaines recommandations apparaîtront ici, à partir de votre activité et de vos résultats réels.",
    "growth.noData": "Pas encore de données",
    "growth.unavailable":
      "Ces données n’ont pas pu se charger. Les autres outils restent disponibles.",
    "growth.retry": "Réessayer",
    "growth.schedule": "Le travail régulier d’Ada",
    "growth.article": "Article hebdomadaire",
    "growth.seo_insight": "Recommandations SEO",
    "growth.weekly_report": "Bilan hebdomadaire",
    "growth.seo_site_report_cycle": "Analyse SEO",
    "growth.article_research_cycle": "Recherche pour les articles",
    "growth.social_post": "Publications sociales",
    "growth.scheduled": "Planifié",
    "growth.notScheduled": "Non planifié",
    "growth.next": "Prochain passage",
    "growth.manageSchedule": "Voir le programme avec Ada",
    "growth.ga4": "Google Analytics · GA4",
    "growth.gsc": "Google Search Console",
    "growth.dataforseo": "Recherche de mots-clés · DataForSEO",
    "growth.ga4Note": "Visiteurs, pages populaires et origine des visites.",
    "growth.gscNote": "Recherches, clics Google et visibilité du site.",
    "growth.dataforseoNote":
      "Des recherches pour choisir vos mots-clés, articles utiles et opportunités SEO.",
    "growth.has_data": "Données disponibles",
    "growth.collecting": "Propriété configurée",
    "growth.configured": "Fournisseur configuré",
    "growth.verification_required": "Vérification requise",
    "growth.not_configured": "À configurer",
    "growth.setupNote":
      "Ada s’occupe de la configuration et de l’analyse. Les statuts reflètent votre site, sans données de démonstration. Les accès et accords nécessaires sont demandés avant la configuration.",
    "growth.setup": "Vérifier la configuration avec Ada",
    "growth.updated": "Mis à jour",
    "growth.approval":
      "Les articles et changements restent des brouillons jusqu’à votre accord.",
    "growth.queries": "Ce que les gens recherchent",
    "growth.keyword": "Mot-clé",
    "growth.market": "Marché",
    "growth.researched": "Recherches effectuées",
    "growth.volume": "Recherches mensuelles",
    "growth.competition": "Concurrence",
    "growth.position": "Position",
    "growth.pages": "Pages populaires",
    "growth.channels": "Origine des visites",
    "growth.articles": "Articles à vérifier",
    "growth.ideas": "Idées d’articles",
    "growth.weeklyReports": "Bilans hebdomadaires",
    "growth.monthlyReports": "Rapports SEO",
    "growth.emptyArticles":
      "Les articles d’Ada apparaîtront ici pour vérification. Le blog reste accessible dans Gérer.",
    "growth.emptyResearch":
      "Vos mots-clés apparaîtront ici après les premières recherches.",
    "growth.emptyReports":
      "Les rapports apparaîtront ici quand Ada les aura terminés.",
    "growth.openBlog": "Ouvrir le blog",
    "growth.activity": "Toute l’activité",
    "growth.askPrompt":
      "Explique les résultats de mon site et recommande les prochaines actions les plus utiles. Appuie-toi sur les analyses et recherches disponibles, identifie les données manquantes et explique avant de modifier quoi que ce soit.",
    "growth.setupPrompt":
      "Vérifie la configuration de Google Analytics, Search Console et de la recherche de mots-clés pour mon site. Explique ce qui est connecté, les accès ou accords manquants et les prochaines étapes. Ne crée pas de comptes et ne lance pas de recherche payante sans mon accord.",
    "growth.schedulePrompt":
      "Vérifie le programme des articles hebdomadaires, recommandations SEO, recherches de mots-clés et bilans. Montre ce qui est activé et propose un calendrier utile. Garde les articles et changements en brouillon pour mon accord.",
  },
  es: {
    "growth.title": "Crecimiento",
    "growth.overview": "Resumen",
    "growth.analytics": "Detalle de analítica",
    "growth.analyticsIntro": "Explora el historial de GA4 y Search Console que Ada usa para recomendar mejoras. El resumen sigue centrado en qué hacer después.",
    "growth.analyticsPrompt": "Interpreta el historial de GA4 y Search Console de mi sitio. Explica la tendencia más importante, qué significa para mi negocio y qué recomienda Ada después.",
    "growth.interpretWithAda": "Interpretar con Ada",
    "growth.ga4History": "Historial de visitas",
    "growth.gscHistory": "Historial de búsqueda",
    "growth.history": "Historial diario",
    "growth.historyNote": "El periodo seleccionado, actualizado directamente desde la propiedad conectada.",
    "growth.date": "Fecha",
    "growth.views": "Páginas vistas",
    "growth.engagement": "Tasa de interacción",
    "growth.ctr": "Tasa de clics",
    "growth.events": "Eventos",
    "growth.count": "Cantidad",
    "growth.devices": "Dispositivos",
    "growth.countries": "Países",
    "growth.search": "Búsquedas y palabras clave",
    "growth.content": "Artículos e informes",
    "growth.connections": "Conexiones",
    "growth.days": "días",
    "growth.refresh": "Actualizar",
    "growth.visitors": "Visitantes",
    "growth.sessions": "Visitas",
    "growth.clicks": "Clics de Google",
    "growth.impressions": "Apariciones en Google",
    "growth.traffic": "Cómo te encuentran",
    "growth.recommendations": "Recomendaciones de Ada",
    "growth.ask": "Hablar con Ada",
    "growth.noRecommendations":
      "Tus próximas recomendaciones aparecerán aquí, basadas en tu negocio y sus resultados reales.",
    "growth.noData": "Todavía no hay datos",
    "growth.unavailable":
      "No se pudieron cargar estos datos. Las demás herramientas siguen disponibles.",
    "growth.retry": "Reintentar",
    "growth.schedule": "El trabajo continuo de Ada",
    "growth.article": "Artículo semanal",
    "growth.seo_insight": "Recomendaciones SEO",
    "growth.weekly_report": "Informe semanal",
    "growth.seo_site_report_cycle": "Análisis SEO",
    "growth.article_research_cycle": "Investigación para artículos",
    "growth.social_post": "Publicaciones sociales",
    "growth.scheduled": "Programado",
    "growth.notScheduled": "Sin programar",
    "growth.next": "Próxima ejecución",
    "growth.manageSchedule": "Revisar el plan con Ada",
    "growth.ga4": "Google Analytics · GA4",
    "growth.gsc": "Google Search Console",
    "growth.dataforseo": "Palabras clave · DataForSEO",
    "growth.ga4Note": "Visitantes, páginas populares y origen de las visitas.",
    "growth.gscNote": "Búsquedas, clics de Google y visibilidad.",
    "growth.dataforseoNote":
      "Investigación para elegir palabras clave, artículos útiles y oportunidades SEO.",
    "growth.has_data": "Datos disponibles",
    "growth.collecting": "Propiedad configurada",
    "growth.configured": "Proveedor configurado",
    "growth.verification_required": "Falta verificación",
    "growth.not_configured": "Falta configurar",
    "growth.setupNote":
      "Ada administra la configuración y el análisis. Los estados corresponden a tu sitio, no a una demo. Se solicitan los accesos y aprobaciones necesarios antes de configurar.",
    "growth.setup": "Revisar conexiones con Ada",
    "growth.updated": "Actualizado",
    "growth.approval":
      "Los artículos y cambios se quedan como borradores hasta que los apruebes.",
    "growth.queries": "Lo que busca la gente",
    "growth.keyword": "Palabra clave",
    "growth.market": "Mercado",
    "growth.researched": "Investigaciones",
    "growth.volume": "Búsquedas mensuales",
    "growth.competition": "Competencia",
    "growth.position": "Posición",
    "growth.pages": "Páginas populares",
    "growth.channels": "Origen de las visitas",
    "growth.articles": "Artículos por revisar",
    "growth.ideas": "Ideas de artículos",
    "growth.weeklyReports": "Informes semanales",
    "growth.monthlyReports": "Informes SEO",
    "growth.emptyArticles":
      "Los artículos de Ada aparecerán aquí para revisión. Tu blog sigue disponible en Administrar.",
    "growth.emptyResearch":
      "Tus palabras clave aparecerán aquí después de la primera investigación.",
    "growth.emptyReports":
      "Los informes aparecerán aquí cuando Ada los termine.",
    "growth.openBlog": "Abrir blog",
    "growth.activity": "Toda la actividad",
    "growth.askPrompt":
      "Explica los resultados de mi sitio y recomienda los siguientes pasos de mayor impacto. Usa los análisis e investigaciones disponibles, identifica los datos faltantes y explica antes de cambiar algo.",
    "growth.setupPrompt":
      "Revisa la configuración de Google Analytics, Search Console e investigación de palabras clave para mi sitio. Explica qué está conectado, qué accesos o aprobaciones faltan y los siguientes pasos. No crees cuentas ni inicies investigación de paga sin mi aprobación.",
    "growth.schedulePrompt":
      "Revisa el plan de artículos semanales, recomendaciones SEO, investigación de palabras clave e informes. Muestra qué está activado y propón un calendario útil. Mantén los artículos y cambios como borradores para mi aprobación.",
  },
};
