// Human language first; provider terminology lives in drill-downs.
export const growthWorkspaceCopy: Record<string, Record<string, string>> = {
  en: {
    additionalMetrics: "More engagement metrics",
    newVisitors: "New visitors",
    engagedVisits: "Engaged visits",
    averageDuration: "Avg. visit duration · seconds",
    overview: "Ada’s brief",
    analytics: "Traffic & search",
    search: "Keywords",
    health: "Site health",
    content: "Content",
    connections: "Connections",
    filter: "Search this table…",
    rows: "results",
    export: "Export CSV",
    noMatches: "No matching results.",
    previous: "Previous page",
    nextPage: "Next page",
    exploreChart: "Hover or focus a point",
    chartNote: "Reported days only · missing dates are gaps",
    vsPrevious: "vs previous period",
    source: "Data source",
    trafficTab: "Website visits",
    searchTab: "Google visibility",
    metric: "Chart metric",
    dimension: "Explore by",
    exploreData: "Explore the data",
    loading: "Loading your data…",
    partialError:
      "Some reports could not load. Available reports are shown below.",
    coverage:
      "Reported rows for this period, not an exhaustive Google export. Google may omit low-volume search terms. No rows are invented.",
    researchTitle: "Find your next opportunity",
    researchNote:
      "Demand, difficulty and intent from research already completed for your business. Viewing this page does not launch paid research.",
    healthTitle: "A healthier website",
    healthNote:
      "Issues from your latest completed crawl. Ask Ada to explain the impact and prepare a fix for review.",
    keywordLibrary: "Your keyword library",
    allMarkets: "All markets",
    difficulty: "SEO difficulty",
    intent: "Search intent",
    paidCompetition: "Ad competition",
    metricNote:
      "Difficulty: organic ranking, 0–100. Ad competition: paid search, not SEO difficulty. CPC: provider-reported cost per click. — means unreported, not zero.",
    selectedKeyword: "Keyword detail",
    closeDetail: "Close keyword detail",
    demandHistory: "Monthly demand",
    demandNote:
      "Provider monthly observations in stored order; no dates are inferred.",
    planKeyword: "Build a plan with Ada",
    competitorTitle: "Domain landscape",
    domain: "Domain",
    rankedKeywords: "Ranking keywords",
    estimatedTraffic: "Est. organic traffic",
    estimateNote:
      "DataForSEO estimates, not your measured GA4 traffic. Only domains in your completed research appear here.",
    backlinksTitle: "Backlink overview",
    links: "Backlinks",
    referringDomains: "Linking domains",
    researchHistory: "Research history & seeds",
    seeds: "Research seeds",
    language: "Language",
    state: "Status",
    healthScore: "Crawl health / 100",
    crawledPages: "Pages crawled",
    issues: "Issues to investigate",
    noCrawl: "No completed crawl yet",
    noIssues: "No issues returned by the latest crawl.",
    severity: "Severity",
    allSeverities: "All severities",
    CRITICAL: "Critical",
    WARNING: "Warning",
    INFO: "Information",
    issueType: "Issue type",
    description: "What to investigate",
    briefNote: "Your latest saved analysis · not a live report",
    briefPeriodNote:
      "Live metrics for this period. Ada’s saved brief may cover a different period.",
    readyForReview: "Your review queue",
    openContent: "Review content",
    performance: "Performance at a glance",
    researchPrompt:
      "Review my existing keyword, domain and backlink research. Relate the evidence to my business goals; distinguish estimates from actual traffic. Recommend a content or page plan for approval, identify missing evidence, and do not start paid research without approval.",
    healthPrompt:
      "Review the latest completed website crawl. Explain which issues affect visitors or search visibility and recommend an ordered fix plan. Prepare changes for approval; do not publish or launch a paid crawl without approval.",
  },
  fr: {
    additionalMetrics: "Autres indicateurs d’engagement",
    newVisitors: "Nouveaux visiteurs",
    engagedVisits: "Visites engagées",
    averageDuration: "Durée moyenne · secondes",
    overview: "Le point avec Ada",
    analytics: "Visites et recherche",
    search: "Mots-clés",
    health: "Santé du site",
    content: "Contenu",
    connections: "Connexions",
    filter: "Rechercher dans ce tableau…",
    rows: "résultats",
    export: "Exporter CSV",
    noMatches: "Aucun résultat correspondant.",
    previous: "Page précédente",
    nextPage: "Page suivante",
    exploreChart: "Survolez ou sélectionnez un point",
    chartNote: "Jours renseignés · les dates manquantes restent vides",
    vsPrevious: "vs période précédente",
    source: "Source des données",
    trafficTab: "Visites du site",
    searchTab: "Visibilité Google",
    metric: "Indicateur du graphique",
    dimension: "Explorer par",
    exploreData: "Explorer les données",
    loading: "Chargement de vos données…",
    partialError:
      "Certains rapports n’ont pas pu se charger. Les rapports disponibles restent visibles.",
    coverage:
      "Données renvoyées pour cette période, pas un export Google exhaustif. Google peut omettre les recherches peu fréquentes. Aucune donnée n’est inventée.",
    researchTitle: "Trouver votre prochaine opportunité",
    researchNote:
      "Demande, difficulté et intention issues des recherches déjà réalisées pour votre activité. Cette page ne lance aucune recherche payante.",
    healthTitle: "Un site en meilleure santé",
    healthNote:
      "Problèmes du dernier audit terminé. Demandez à Ada d’expliquer leur impact et de préparer une correction à vérifier.",
    keywordLibrary: "Votre bibliothèque de mots-clés",
    allMarkets: "Tous les marchés",
    difficulty: "Difficulté SEO",
    intent: "Intention",
    paidCompetition: "Concurrence publicitaire",
    metricNote:
      "Difficulté : référencement naturel, de 0 à 100. Concurrence : annonces payantes, pas difficulté SEO. CPC : coût par clic indiqué par le fournisseur. — signifie non renseigné, pas zéro.",
    selectedKeyword: "Détail du mot-clé",
    closeDetail: "Fermer le détail",
    demandHistory: "Demande mensuelle",
    demandNote:
      "Observations mensuelles dans leur ordre enregistré ; aucune date n’est supposée.",
    planKeyword: "Préparer un plan avec Ada",
    competitorTitle: "Paysage des domaines",
    domain: "Domaine",
    rankedKeywords: "Mots-clés positionnés",
    estimatedTraffic: "Trafic naturel estimé",
    estimateNote:
      "Estimations DataForSEO, pas vos visites mesurées par GA4. Seuls les domaines de vos recherches terminées apparaissent ici.",
    backlinksTitle: "Vue des liens entrants",
    links: "Liens entrants",
    referringDomains: "Domaines référents",
    researchHistory: "Historique et pistes de recherche",
    seeds: "Pistes de recherche",
    language: "Langue",
    state: "État",
    healthScore: "Santé de l’audit / 100",
    crawledPages: "Pages analysées",
    issues: "Problèmes à examiner",
    noCrawl: "Aucun audit terminé",
    noIssues: "Aucun problème renvoyé par le dernier audit.",
    severity: "Gravité",
    allSeverities: "Toutes les gravités",
    CRITICAL: "Critique",
    WARNING: "Attention",
    INFO: "Information",
    issueType: "Type de problème",
    description: "Point à examiner",
    briefNote: "Dernière analyse enregistrée · pas un rapport en direct",
    briefPeriodNote:
      "Indicateurs actuels de cette période. Le point d’Ada peut couvrir une autre période.",
    readyForReview: "À vérifier",
    openContent: "Vérifier le contenu",
    performance: "Les résultats en un coup d’œil",
    researchPrompt:
      "Examine les recherches existantes de mots-clés, domaines et liens entrants. Relie les résultats aux objectifs de mon activité et distingue estimations et visites réelles. Propose un plan de contenu ou de pages à valider, précise les données manquantes et ne lance pas de recherche payante sans mon accord.",
    healthPrompt:
      "Examine le dernier audit terminé du site. Explique les problèmes qui touchent les visiteurs ou la visibilité Google et propose un plan de correction priorisé. Prépare les modifications à valider ; ne publie pas et ne lance pas d’audit payant sans mon accord.",
  },
  es: {
    additionalMetrics: "Más indicadores de interacción",
    newVisitors: "Visitantes nuevos",
    engagedVisits: "Visitas con interacción",
    averageDuration: "Duración promedio · segundos",
    overview: "El resumen de Ada",
    analytics: "Visitas y búsquedas",
    search: "Palabras clave",
    health: "Salud del sitio",
    content: "Contenido",
    connections: "Conexiones",
    filter: "Buscar en esta tabla…",
    rows: "resultados",
    export: "Exportar CSV",
    noMatches: "No hay resultados que coincidan.",
    previous: "Página anterior",
    nextPage: "Página siguiente",
    exploreChart: "Pasa el cursor o selecciona un punto",
    chartNote: "Solo días reportados · las fechas faltantes quedan vacías",
    vsPrevious: "vs periodo anterior",
    source: "Fuente de datos",
    trafficTab: "Visitas al sitio",
    searchTab: "Visibilidad en Google",
    metric: "Indicador del gráfico",
    dimension: "Explorar por",
    exploreData: "Explorar los datos",
    loading: "Cargando tus datos…",
    partialError:
      "Algunos informes no se pudieron cargar. Los informes disponibles siguen visibles.",
    coverage:
      "Datos reportados para este periodo, no una exportación completa de Google. Google puede omitir búsquedas poco frecuentes. No se inventan datos.",
    researchTitle: "Encuentra tu próxima oportunidad",
    researchNote:
      "Demanda, dificultad e intención de investigaciones ya realizadas para tu negocio. Abrir esta página no inicia investigaciones de pago.",
    healthTitle: "Un sitio más saludable",
    healthNote:
      "Problemas del último rastreo terminado. Pídele a Ada que explique su impacto y prepare una corrección para revisar.",
    keywordLibrary: "Tu biblioteca de palabras clave",
    allMarkets: "Todos los mercados",
    difficulty: "Dificultad SEO",
    intent: "Intención de búsqueda",
    paidCompetition: "Competencia publicitaria",
    metricNote:
      "Dificultad: posicionamiento orgánico, de 0 a 100. Competencia: anuncios pagados, no dificultad SEO. CPC: costo por clic reportado por el proveedor. — significa sin dato, no cero.",
    selectedKeyword: "Detalle de palabra clave",
    closeDetail: "Cerrar detalle",
    demandHistory: "Demanda mensual",
    demandNote:
      "Observaciones mensuales en el orden guardado; no se suponen fechas.",
    planKeyword: "Preparar un plan con Ada",
    competitorTitle: "Panorama de dominios",
    domain: "Dominio",
    rankedKeywords: "Palabras posicionadas",
    estimatedTraffic: "Tráfico orgánico estimado",
    estimateNote:
      "Estimaciones de DataForSEO, no tus visitas reales de GA4. Solo aparecen dominios de investigaciones terminadas.",
    backlinksTitle: "Resumen de enlaces entrantes",
    links: "Enlaces entrantes",
    referringDomains: "Dominios de referencia",
    researchHistory: "Historial y temas de investigación",
    seeds: "Temas de investigación",
    language: "Idioma",
    state: "Estado",
    healthScore: "Salud del rastreo / 100",
    crawledPages: "Páginas rastreadas",
    issues: "Problemas por investigar",
    noCrawl: "Todavía no hay un rastreo terminado",
    noIssues: "El último rastreo no reportó problemas.",
    severity: "Gravedad",
    allSeverities: "Todas las gravedades",
    CRITICAL: "Crítico",
    WARNING: "Advertencia",
    INFO: "Información",
    issueType: "Tipo de problema",
    description: "Qué investigar",
    briefNote: "Tu último análisis guardado · no es un informe en tiempo real",
    briefPeriodNote:
      "Indicadores actuales de este periodo. El resumen de Ada puede cubrir otro periodo.",
    readyForReview: "Pendiente de tu revisión",
    openContent: "Revisar contenido",
    performance: "Resultados de un vistazo",
    researchPrompt:
      "Revisa la investigación existente de palabras clave, dominios y enlaces. Relaciona los datos con los objetivos de mi negocio; distingue estimaciones de visitas reales. Recomienda un plan de contenido o páginas para aprobar, identifica los datos faltantes y no inicies investigación de pago sin mi aprobación.",
    healthPrompt:
      "Revisa el último rastreo terminado del sitio. Explica qué problemas afectan a los visitantes o la visibilidad en Google y recomienda un plan de corrección priorizado. Prepara cambios para aprobar; no publiques ni inicies un rastreo de pago sin mi aprobación.",
  },
};
