/** Plain-language owner chrome. Spanish uses Mexican usage. */
export const ownerCopy: Record<string, Record<string, string>> = {
  en: {
    'owner.navigation': 'Your website workspace', 'owner.workspace': 'Workspace', 'owner.activity': 'Activity',
    'owner.manage': 'Manage', 'owner.manageTitle': 'Your website, your controls.',
    'owner.manageIntro': 'Ask Ada for everyday changes. These tools are here when you want to do something yourself.',
    'owner.content': 'Content', 'owner.library': 'Photos & files', 'owner.gallery': 'Gallery', 'owner.galleryTitle': 'Image library', 'owner.galleryIntro': 'Keep the images for your site in one place. Pick one to bring it into a conversation with Ada.', 'owner.galleryUseInChat': 'Use in Ada', 'owner.galleryOpenPayload': 'Open full library', 'owner.galleryCount': 'images', 'owner.advanced': 'Advanced options',
    'owner.close': 'Close', 'owner.openSite': 'Visit website',
    'owner.connection.checking': 'Connecting to Ada', 'owner.connection.connected': 'Ada is connected',
    'owner.connection.unavailable': 'Ada is unavailable',
    'owner.heading': 'A little conversation. A better website.',
    'owner.promise': 'Tell Ada what you need. Review the result. Make it live when you’re ready.',
    'owner.website': 'Website', 'owner.pageOptions': 'Page options', 'owner.editManually': 'Edit this page yourself',
    'owner.quickEditing': 'Enable editing in the preview', 'owner.publishChanges': 'Publish changes',
    'owner.readyReview': 'Changes to review', 'owner.notLive': 'Not live until you approve',
    'owner.websitePreview': 'Website preview', 'owner.previewHint': 'Choose a page to give Ada context',
    'owner.assistantRole': 'Your website operator', 'owner.businessContext': 'Business context',
    'owner.welcome': 'What would you like to improve?', 'owner.welcomeNew': 'Let’s start with your business.',
    'owner.welcomeNote': 'A new service, better words, a different look. Tell me what matters, and we’ll work on it together.',
    'owner.improvePage': 'Improve this page', 'owner.improvePrompt': 'Review this page and suggest the most useful improvements for my business. Explain your recommendations before making changes.',
    'owner.writeUpdate': 'Update the content', 'owner.newPage': 'Add a page',
    'owner.seeProgress': 'See what Ada is doing', 'owner.composerNote': 'Ada prepares the changes. You decide what goes live.',
    'owner.reconnectNote': 'Your website is safe. Try reconnecting to continue with Ada.', 'owner.retry': 'Reconnect',
    'owner.publishTitle': 'Ready to make this live?', 'owner.publishNote': 'The reviewed changes on this page will be visible to your visitors.',
    'owner.keepReviewing': 'Keep reviewing',
  },
  fr: {
    'owner.navigation': 'Votre espace de travail', 'owner.workspace': 'Mon site', 'owner.activity': 'Activité',
    'owner.manage': 'Gérer', 'owner.manageTitle': 'Votre site, vos commandes.',
    'owner.manageIntro': 'Confiez les changements du quotidien à Ada. Ces outils sont là quand vous voulez intervenir vous-même.',
    'owner.content': 'Contenu', 'owner.library': 'Photos et fichiers', 'owner.gallery': 'Galerie', 'owner.galleryTitle': 'Bibliothèque d’images', 'owner.galleryIntro': 'Gardez les images de votre site au même endroit. Choisissez-en une pour l’ajouter à une conversation avec Ada.', 'owner.galleryUseInChat': 'Utiliser avec Ada', 'owner.galleryOpenPayload': 'Ouvrir la bibliothèque complète', 'owner.galleryCount': 'images', 'owner.advanced': 'Options avancées',
    'owner.close': 'Fermer', 'owner.openSite': 'Voir le site',
    'owner.connection.checking': 'Connexion à Ada', 'owner.connection.connected': 'Ada est connectée',
    'owner.connection.unavailable': 'Ada est indisponible',
    'owner.heading': 'Un peu de conversation. Un meilleur site.',
    'owner.promise': 'Dites à Ada ce qu’il vous faut. Vérifiez le résultat. Publiez quand vous êtes prêt.',
    'owner.website': 'Le site', 'owner.pageOptions': 'Options de la page', 'owner.editManually': 'Modifier cette page vous-même',
    'owner.quickEditing': 'Activer la modification dans l’aperçu', 'owner.publishChanges': 'Publier les changements',
    'owner.readyReview': 'Changements à vérifier', 'owner.notLive': 'Rien n’est publié sans votre accord',
    'owner.websitePreview': 'Aperçu du site', 'owner.previewHint': 'Choisissez une page pour guider Ada',
    'owner.assistantRole': 'Votre partenaire pour le site', 'owner.businessContext': 'Votre activité',
    'owner.welcome': 'Qu’aimeriez-vous améliorer ?', 'owner.welcomeNew': 'Parlons de votre activité.',
    'owner.welcomeNote': 'Un nouveau service, des mots plus justes, un autre style. Dites-moi ce qui compte, on s’en occupe ensemble.',
    'owner.improvePage': 'Améliorer cette page', 'owner.improvePrompt': 'Examine cette page et propose les améliorations les plus utiles pour mon activité. Explique tes recommandations avant de faire des changements.',
    'owner.writeUpdate': 'Actualiser le contenu', 'owner.newPage': 'Ajouter une page',
    'owner.seeProgress': 'Voir ce que fait Ada', 'owner.composerNote': 'Ada prépare les changements. Vous décidez de la publication.',
    'owner.reconnectNote': 'Votre site est en sécurité. Reconnectez-vous pour continuer avec Ada.', 'owner.retry': 'Reconnecter',
    'owner.publishTitle': 'Prêt à publier ?', 'owner.publishNote': 'Les changements vérifiés sur cette page seront visibles par vos visiteurs.',
    'owner.keepReviewing': 'Continuer la vérification',
  },
  es: {
    'owner.navigation': 'Tu espacio de trabajo', 'owner.workspace': 'Mi sitio', 'owner.activity': 'Actividad',
    'owner.manage': 'Administrar', 'owner.manageTitle': 'Tu sitio, tus controles.',
    'owner.manageIntro': 'Pídele a Ada los cambios de todos los días. Estas herramientas están aquí cuando quieras hacerlo tú.',
    'owner.content': 'Contenido', 'owner.library': 'Fotos y archivos', 'owner.gallery': 'Galería', 'owner.galleryTitle': 'Biblioteca de imágenes', 'owner.galleryIntro': 'Guarda las imágenes de tu sitio en un solo lugar. Elige una para llevarla a una conversación con Ada.', 'owner.galleryUseInChat': 'Usar con Ada', 'owner.galleryOpenPayload': 'Abrir biblioteca completa', 'owner.galleryCount': 'imágenes', 'owner.advanced': 'Opciones avanzadas',
    'owner.close': 'Cerrar', 'owner.openSite': 'Visitar el sitio',
    'owner.connection.checking': 'Conectando con Ada', 'owner.connection.connected': 'Ada está conectada',
    'owner.connection.unavailable': 'Ada no está disponible',
    'owner.heading': 'Una conversación. Un mejor sitio.',
    'owner.promise': 'Dile a Ada qué necesitas. Revisa el resultado. Publica cuando estés listo.',
    'owner.website': 'Sitio web', 'owner.pageOptions': 'Opciones de la página', 'owner.editManually': 'Editar esta página tú mismo',
    'owner.quickEditing': 'Activar edición en la vista previa', 'owner.publishChanges': 'Publicar cambios',
    'owner.readyReview': 'Cambios por revisar', 'owner.notLive': 'No se publica nada sin tu aprobación',
    'owner.websitePreview': 'Vista previa del sitio', 'owner.previewHint': 'Elige una página para darle contexto a Ada',
    'owner.assistantRole': 'Tu asistente para el sitio', 'owner.businessContext': 'Tu negocio',
    'owner.welcome': '¿Qué te gustaría mejorar?', 'owner.welcomeNew': 'Empecemos por tu negocio.',
    'owner.welcomeNote': 'Un servicio nuevo, mejores textos, otro estilo. Dime qué importa y lo trabajamos juntos.',
    'owner.improvePage': 'Mejorar esta página', 'owner.improvePrompt': 'Revisa esta página y sugiere las mejoras más útiles para mi negocio. Explica tus recomendaciones antes de hacer cambios.',
    'owner.writeUpdate': 'Actualizar contenido', 'owner.newPage': 'Agregar una página',
    'owner.seeProgress': 'Ver qué está haciendo Ada', 'owner.composerNote': 'Ada prepara los cambios. Tú decides qué se publica.',
    'owner.reconnectNote': 'Tu sitio está seguro. Intenta reconectarte para continuar con Ada.', 'owner.retry': 'Reconectar',
    'owner.publishTitle': '¿Listo para publicar?', 'owner.publishNote': 'Los cambios revisados en esta página serán visibles para tus visitantes.',
    'owner.keepReviewing': 'Seguir revisando',
  },
}
